### ISSUE TITLE
CPCSS for specific pages (using metabox)

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2377]
## Why are we doing this feature?

The feature proposal is currently to add page specific CPCSS to any post type that is public and has an editor interface (i.e. the WP Rocket options metabox will be available). It's very common for a lot of publishers to have custom page layouts. We have many examples on our WP Rocket website (example: <https://wp-rocket.me/features>). 

Having page specific CPCSS will benefit websites with such custom layouts. 

## User expectations and experience 

Users will be able to generate custom CPCSS for their pages in one click. 

## How will we do this feature?

- In the beginning, the page uses the default CPCSS. At this point, we need only one button that says, "Generate CPCSS For This Page".
- On clicking it, CPCSS is generated and saved with other CPCSS CSS files as post_type-id.css (example page-19.css)
- "Generate CPCSS" now renamed to "Regenerate CPCSS". Click it will regenerate the CPCSS. 
- Below it a small link says "Disable custom CPCSS". This will delete the custom generated CPCSS and fall back to the common CPCSS for the post type. 

UI being discussed here: <https://wp-media.slack.com/archives/CFSCRLVGB/p1580933950000100>

Technical overview

Flowchart for admin/front: <https://drive.google.com/file/d/1K5vPc0_JURHWiWX7KujZAo1OhJczZbpj/view?usp=sharing>

  
**Code**
- [x] [UI](https://github.com/wp-media/wp-rocket/issues/2443)
- [x] [AJAX](https://github.com/wp-media/wp-rocket/issues/2444)
- [x] [CPCSS generation](https://github.com/wp-media/wp-rocket/issues/2445)
- [x] [CPCSS deletion](https://github.com/wp-media/wp-rocket/issues/2446)
- [x] [Update common CPCSS deletion](https://github.com/wp-media/wp-rocket/issues/2447)
- [x] [Front](https://github.com/wp-media/wp-rocket/issues/2448)

- New REST API endpoint for the CPCSS, with a subscriber class to register it, handle the validation & callbacks
- New JS script on the edit.php page to add the AJAX handlers
- New subscriber for the CPCSS metabox
- Update CPCSS subscriber to use the specific CPCSS when it exists
- Update clean method from CPCSS class, to ignore pages CPCSS
- Add automated tests for all the above
  
**Estimate**

~~2 weeks~~ 1 week of work with Tonya (doing the JS) and Remy doing the plugin work.

## Risks

Risk should be minimal because: 

- We already generate CPCSS using the same tool. So we are not inviting additional risk. 

- This is an opt-in feature that the user initiates. They will know what is broken immediately and will be able to fix it. 

## Testing

- If Optimize CSS delivery is disabled, make sure that the buttons do not show up or is disabled. This is being discussed here: <https://wp-media.slack.com/archives/CFSCRLVGB/p1580934249001600>

- Generate the CPCSS for the page. Assuming the page layout is different from others, see if the generated CPCSS works and is different from the default one. 

- Change the page layout and regenerate the CPCSS. Make sure regeneration works. 

- Clear the CPCSS and make sure that it falls back to the default one. 

- If the user disabled "Optimize CSS delivery" via the meta box make sure no CPCSS is delivered on the front end. 

- UI Spec: https://github.com/wp-media/wp-rocket/issues/2443#issuecomment-617579591

- Test the UI in Block editor and Classic editor (https://github.com/wp-media/wp-rocket/issues/2443#issuecomment-619200123)

## Documentation and Translations

<What changes or additions will need to be made to documentation and translations?>

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4109814
