### ISSUE TITLE
Create a specific CPCSS for mobile

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2378]
## Why are we doing this feature?

Currently, WP Rocket generates and uses the same CPCSS for desktop and mobile. However, some websites have mobile specific themes and can benefit from having mobile specific CPCSS. 

## How will we do this feature?

- To serve specific CPCSS for mobile the “Separate cache for mobile” should be enabled. 

- We will only generate CPCSS for mobile if customer enables, “Separate cache for mobile”. 

- If the customer isn’t using “Separate cache for mobile”, then the theme is already responsive. The CPCSS generated for desktop is already valid for mobile. This is how many customers function as of now. 

- If “Separate cache for mobile” is enabled after enabling Optimize CSS delivery, then the mobile CPCSS will be generated automatically at that point. 

- An invisible database option to be added similar to how we handled cache_ssl. This option can be set as [1 for new installs](https://github.com/wp-media/wp-rocket/blob/281eb493f44e873a9685f379cec701e8ebcf3532/inc/admin/upgrader.php#L172) and as 0 for upgrades. 

- For existing customers who update, the mobile CPCSS will be an opt-in using a single use helper plugin. The helper plugin will set the invisible database option to 1. 

- When mobile CPCSS is disabled (i.e. invisible database option is set to 0), the current behaviour of serving desktop CPCSS to mobile will continue. 

- Fallback CPCSS works the same as it works now. Will be for both desktop and mobile. 

- There are no changes to be made in the UI including admin notices. 

### Tasks
- [x] [Settings](https://github.com/wp-media/wp-rocket/issues/2610)
- [x] [Tools](https://github.com/wp-media/wp-rocket/issues/2611)
- [x] [Generation](https://github.com/wp-media/wp-rocket/issues/2612)
- [x] [Frontend](https://github.com/wp-media/wp-rocket/issues/2613)

## User expectations and experience

- Nothing changes in the WP Rocket UI for the user. 

- Depending on the choice the user makes with the “Separate cache for mobile” option, WP Rocket generates Desktop and mobile CPCSS. 

- Everything remains completely transparent to the user. 

<p></p>

**Notes from 3.5 version discussion on 27-Nov-2019:** 

<p></p>

- We decided not to change anything in the UI including the UI notice. Everything is transparent to the user. 

- For existing customers, mobile CPCSS will be an opt-in via a filter and helper plugin. This could be a database setting (similar to what we did for SSL Cache). We do not get enough mobile specific CPCSS requests. So don't fix that ain't broken. 

- For new customers, mobile CPCSS will be enabled by default and will be an opt-out via the filter or database setting. 

## Risks

To avoid any risks we will not change anything for existing users. For them mobile CPCSS will be an opt-in. 

## Testing

- Completely new install

- Enable "Separate cache for mobile".

- Enable Optimize CSS delivery .

- CPCSS for both desktop and mobile will be generated.

- Visiting the mobile and desktop versions will show different CPCSS.

- Disable "Separate cache for mobile". 

- Desktop CPCSS will be served on mobile. 

- Upgrade from pre-3.7 to 3.7

- Enable "Separate cache for mobile".

- Regenerate CPCSS

- Only desktop CPCSS is generated

- Use the helper plugin to enable the option for Mobile CPCSS

- Disable "Separate cache for mobile" and then enable it again. 

- Mobile CPCSS should be enabled automatically now. 

- Use the helper plugin to disable the option for Mobile CPCSS

- Desktop CPCSS should be served on mobile as before. 

- Disable Mobile CPCSS completely

- Install the helper - <https://github.com/wp-media/wp-rocket-helpers/tree/master/static-files/wp-rocket-static-no-opt-css-mobile>

- Generate mobile CPCSS.

- Make sure no CPCSS is served on mobile.

## Documentation and Translations

- Helper plugin to enable and disable mobile specific CPCSS to be documented here: <https://docs.wp-rocket.me/article/1266-optimize-css-delivery>

- If a customer wants to disable CPCSS for mobile completely, they can use the current helper plugin - <https://github.com/wp-media/wp-rocket-helpers/tree/master/static-files/wp-rocket-static-no-opt-css-mobile>

- Information about this will be sent out in the announcement email for 3.7

<p></p>

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4109850

**Comment by Tabrisrp** [comment]
> For existing customers who update, the mobile CPCSS will be an opt-in using a single use helper plugin. The helper plugin will set the invisible database option to 1.

Instead of a helper plugin, how about this:
- On the tools tab of WP Rocket settings
- If both "Optimize CSS Delivery" & "Create a separate cache for mobile devices" are checked, but the new invisible option is set to `0`, display a button + description to switch it on
- If any of the options are not enabled, or the invisible option is already set to `1`, nothing is displayed

This prevent users from going through all the process of installing, enabling, disabling a plugin just for that.

**Comment by GeekPress** [comment]
@Tabrisrp I do love the idea. Let's go with your suggestion!

**Comment by Tabrisrp** [comment]
Currently blocked by PR #2609 

This PR has issues with the DELETE HTTP request being blocked by some security plugins. Discussion ongoing to decide how to move forward.

**Comment by GeekPress** [comment]
@hellofromtonya @Tabrisrp I guess since we closed #2609, this epic isn't blocked anymore?

**Comment by Tabrisrp** [comment]
We can start CPCSS For mobile epic, part 1, 2 & 4, if we branch from `feature/cpcss-for-specific-pages`. But part 3 requires the CPCSS refactor that Ahmed is finishing currently

**Comment by arunbasillal** [comment]
Some feedback regarding - https://github.com/wp-media/wp-rocket/issues/2378#issuecomment-623552306 (Adding the option to `Tools` section)

- The whole idea of not doing a UI was because "existing customers who use CPCSS do not need this option". For responsive themes, the current CPCSS should work just fine. 
- If we are talking about doing a UI, why not keep it in File Optimization tab itself? As a sub-option to Optimize CSS delivery? The tools section doesn't feel like a natural spot for this option. 
- We have a huge number of customers with `separate cache for mobile devices` enabled (as per Mixpanel. We recommended to keep both options enabled when in doubt). Most customers who have enabled `Optimize CSS delivery` will see this. 
- Will the customer be able to disable it once they enable the option? Our customers are going to click something when they see an option. 

I feel like making this easy for customers will generate unnecessary tickets. A helper plugin that enables it on activation is at par with the other helper plugins we offer and isn't too much of a hassle.

**Comment by Tabrisrp** [comment]
> If we are talking about doing a UI, why not keep it in File Optimization tab itself? As a sub-option to Optimize CSS delivery? The tools section doesn't feel like a natural spot for this option.

Since it's a one-time thing, it's better to having it in Tools. It will also only show if it's potentially needed (option not yet set to `1`).

> Will the customer be able to disable it once they enable the option? Our customers are going to click something when they see an option.

No they won't, the button will only show if the option is set to `0`. Having it in tools like I said above, reduces the urge to click on stuff, as it's away from the places users go most to.

**Comment by GeekPress** [comment]
> I feel like making this easy for customers will generate unnecessary tickets.

Why will it generate unnecessary tickets? Which kind?

**Comment by arunbasillal** [comment]
@GeekPress A disappearing option will be confusing to customers. They enable it and the option will no longer exist. This is poor UX imho.

**Comment by GeekPress** [comment]
@arunbasillal It's not option, it's a button. The difference is important

**Comment by arunbasillal** [comment]
> the button will only show if the option is set to 0. Having it in tools like I said above, reduces the urge to click on stuff, as it's away from the places users go most to.

On clicking the button, the page refreshes (or when the customer revisits the page if the button is ajax), and it's gone.

**Comment by Tabrisrp** [comment]
That's kind of the point though, we just want to give existing user a way to update to the new system for mobile. The logic is exactly the same as with an helper, but integrated in the plugin instead.

**Comment by GeekPress** [comment]
@Tabrisrp Will we have a way to disable the CPCSS for mobile if we don't want to use this feature?

**Comment by Tabrisrp** [comment]
We could have the button be enable/disable if we want. But that would not make sense, because if they can perform both action, why not make it a real option then.

We can always use the `pre_get_rocket_option_async_css_mobile` as the hook to force the value of this option (here to disable we would force to `0`).

**Comment by GeekPress** [comment]
After checking with @webtrainingwheels , I confirm you that we would like to implement a button to activate the CPCSS for mobile for existing customers in the tool section.

And a filter to be able to disable the CPCSS for mobile which could be used for new users and existing who users used the button to activate.

**Comment by GeekPress** [comment]
About the button, I don't think we decided the text / label.

@arunbasillal @Tabrisrp @webtrainingwheels Any ideas?

**Comment by arunbasillal** [comment]
> About the button, I don't think we decided the text / label.
Discussed here: https://wp-media.slack.com/archives/G8L4EE8N9/p1589889552000400
