### ISSUE TITLE
Get rid of the Remove Query Strings option

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2406]
## **What are we proposing to do?**

With this update we are hoping to remove the option from WP Rocket UI: Remove query strings from static resources (File Optimization tab)

How our current option looks like: 

![](https://productboard-files.s3.amazonaws.com/production/attachments/976768d27fe808b09e29ba8df10460fb88a290aa1bc3e6aa1e7a50991f6aabde/image.png)

## **Why are we doing this?**

Ressource: <https://sirv.com/help/resources/remove-query-strings-from-static-resources/>

Here is a GTmetrix test comparison: 

- With query strings: <https://gtmetrix.com/reports/mega.wp-rocket.me/lXacNRNS>
- Without query strings: <https://gtmetrix.com/reports/mega.wp-rocket.me/MCZq51yj>

The scores are exactly the same. GTmetrix no longer recommends this nor takes into account query strings for the grades. 

## **Does query strings affect performance?**

Here are the headers for a second visit to the same page: 

![](https://productboard-files.s3.amazonaws.com/production/attachments/8345278a0a61c0b69fe0b8ead06f81f402e98220cd880363c5737e491767df7b/image.png)

Modern browsers and proxies cache based on headers and not based on the presence of query strings. 

## **User expectations and experience. How will we do this feature?**
From version 3.6, all users will not have this option in WP Rocket UI. 

Both existing and new users will have the same experience. Query strings will come back. But as we know from our research, this isn't going to affect performance. 

Pros:

- Simpler approach
- Easier to implement and maintain

Cons: 

- Higher risk since we don't know what edge cases we are missing.

### Sub-Cards
- [x] [3rd party part](https://github.com/wp-media/wp-rocket/issues/2436)
- [x] [Admin misc part](https://github.com/wp-media/wp-rocket/issues/2433)
- [x] [Facebook & Google Tracking part](https://github.com/wp-media/wp-rocket/issues/2438)
- [x] [Front part](https://github.com/wp-media/wp-rocket/issues/2434)
- [x] [Simple Custom CSS part](https://github.com/wp-media/wp-rocket/issues/2437)
- [x] [Common part](https://github.com/wp-media/wp-rocket/issues/2435)
- [x] [Settings part](https://github.com/wp-media/wp-rocket/issues/2432)
- [x] [Option management part](https://github.com/wp-media/wp-rocket/issues/2431)

## **Risks**

Since we are removing a feature, this should be low risk. The major concern is educating customers. 

## **Testing**

The following is written assuming the second approach is used where we remove query strings for existing and new users. 

**Acceptance Criteria:**

- Update WP Rocket to 3.6. (Existing install had the option "Remove Query Strings" enabled)
- The UI for "Remove Query Strings" is removed. 
- Assets should now have the query strings added to it. 
- When Minify CSS / Minify JS is enabled, these will also have the query strings. 

**What if:** 

We need to think of any possible edge cases. Can't think of anything at the time of writing this. 

## **Documentation and Translations**

- <https://docs.wp-rocket.me/article/56-remove-query-string-from-static-resources>
- <https://wp-rocket.me/features/> (Remove Query Strings is listed as a feature)
- Helper plugin: <https://github.com/wp-media/wp-rocket-helpers/tree/master/static-files/wp-rocket-static-exclude-query-string>

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4074393

**Comment by GeekPress** [comment]
@arunbasillal Thanks for the doc!

About **Existing users** scenario, do we have any reason to keep it?

I mean, how do we exclude a « busted » file from the Minify / Combine options?
If the we are using the original filename, I will suggest to totally remove the option even for existing users?

Why?

1. Deactivating an option with an helper plugin isn't what we can do better in terms of user experience
2. We will have to continue to maintain the code of this feature (unit tests, etc...).

If we know at 100% that this feature isn't helpful in terms of speed and removing it can't cause any issues, we must totally remove the feature (code & UI)

**Comment by thekendog** [comment]
Is this for sure going to happen?  I find this feature useful for doing edits to child theme stylesheets.  I don't supply a version number, rather WP Rocket creates one automatically.  If this feature removal is implemented I'd have to edit the version number each time.  Not a huge deal but just adds an extra step.

**Comment by GeekPress** [comment]
@thekendog Yes we will remove for sure this feature in 3.6. The reason is this option don't help to speed up your loading time. It has been implemented only to please GT Metrix recommandation.

And GT Metrix removed this recommandation.

For these reasons, we don't see a reason to keep this option.

**Comment by arunbasillal** [comment]
@GeekPress I agree with you, which is why I have this as part of the feature doc:

> Arun says: My recommendation is to use the simpler second approach and remove it for everyone.

**Comment by Tabrisrp** [comment]
I'm going to try to break this into tasks to do to remove the feature:

### Core
- [ ] inc/admin/upgrader.php, `rocket_first_install()` function: remove the `remove_query_strings` entry
- [ ] inc/admin/upgrader.php, `rocket_new_upgrade()` function: remove the call to `rocket_clean_cache_busting()`
- [ ] inc/admin/options.php, `rocket_after_save_options()` function: remove the call to `rocket_clean_cache_busting()`
- [ ] inc/admin/ui/notices.php, deprecate the `rocket_warning_busting_cache_dir_permissions()` and remove the related `add_action`
- [ ] inc/classes/class-plugin.php, `load()` method: remove `remove_query_string_subscriber` entry
- [ ] inc/classes/admin/settings/class-beacon.php, `session_data()` method: remove the `remove_query_strings` entry
- [ ] inc/classes/admin/settings/class-beacon.php, `get_suggest()` method: remove the `remove_query_strings` entry
- [ ] inc/classes/admin/settings/class-page.php, `assets_section()` method: remove everything related to the remove query strings option
- [ ] inc/classes/admin/settings/class-settings.php, `sanitize_callback()` method: remove sanitization of the option value
- [ ] inc/classes/ServiceProvider/class-optimization-subscribers.php: remove references to the remove query strings classes
- [ ] inc/classes/optimization/class-remove-query-string.php: remove file
- [ ] inc/classes/subscriber/admin/Deactivation/class-deactivation-intent-subscriber.php, `activate_safe_mode` method: remove the `remove_query_strings` entry
- [ ] inc/classes/subscriber/Optimization/class-remove-query-string-subscriber.php: remove file
- [ ] inc/classes/subscriber/Tools/class-cache-dir-size-check-subscriber.php, `cache_dir_size_check()` method: remove check for the busting folder
- [ ] inc/common/purge.php, `do_admin_post_rocket_purge_cache()` function: remove call to `rocket_clean_cache_busting()`
- [ ] inc/functions/files.php: deprecate the `rocket_clean_cache_busting()` function
- [ ] inc/functions/formatting.php: deprecate `rocket_get_cache_busting_paths()`

### 3rd party compatibility
- [ ] inc/3rd-party/plugins/page-builder/beaver-builder.php, `rocket_beaver_builder_clean_domain()` function: remove the call to `rocket_clean_cache_busting()`
- [ ] inc/3rd-party/themes/avada.php: deprecate `rocket_exclude_avada_dynamic_css()` function and remove related `add_filter`
- [ ] inc/3rd-party/themes/uncode.php: deprecate `rocket_exclude_busting_uncode()` function and remove related `add_filter`
- [ ] inc/classes/subscriber/third-party/plugins/PageBuilder/class-elementor-subscriber.php, `clear_cache()` method: remove call to `rocket_clean_cache_busting()`
- [ ] inc/classes/subscriber/third-party/plugins/Optimization/class-hummingbird-subscriber.php: remove `check_remove_query_strings()` method
- [ ] inc/classes/subscriber/third-party/Themes/class-bridge-subscriber.php, function `maybe_clear_cache()`: remove checks for remove query strings and call to `rocket_clean_cache_busting()`

### Automated tests
We don't have any yet, but we could have some added in between, notably with PR #2392, so those will need to be removed

### Special cases
- [ ] inc/3rd-party/plugins/simple-custom-css.php: update and test code accordingly to make sure the compatibility still works
- [ ] inc/classes/subscriber/class-facebook-tracking-cache-busting-subscriber.php, `after_rocket_clean_cache_busting` callback `delete_cache()`
- [ ] inc/classes/subscriber/class-google-tracking-cache-busting-subscriber.php, `after_rocket_clean_cache_busting` callback `delete_tracking_cache()`

The 2 last cases are the ones that need discussion: do we want to preserve the current behaviour, i.e. removing the local cache file when purge the whole cache from the admin? If yes, how?

@arunbasillal @GeekPress @Screenfeed @hellofromtonya input appreciated for the above ^

**Comment by GeekPress** [comment]
@Tabrisrp If we don't do that anymore, when do these files will be regenerated? And how the customer will be able to purge the files themself?

**Comment by Tabrisrp** [comment]
> when do these files will be regenerated?
They would be regenerated based on the cron jobs we have running to do that, currently on a weekly basis.

> And how the customer will be able to purge the files themself?
Yes that's the issue, they could not. I'm wondering what's the best way to still offer this. For example:
- Continue to delete them when we clear the whole cache from the admin
- Add a "clear cache" button for each of them on the Add-Ons section, to be able to clear them individually and on-demand
- other ideas?

**Comment by Screenfeed** [comment]
Instead of removing `rocket_clean_cache_busting()`, why not replacing it by a new function that only contains a `do_action()` (and hook everything here)?

**Comment by arunbasillal** [comment]
- We [haven't seen any cases](https://wp-media.slack.com/archives/C08N8J6VC/p1584544820184400) where the customer needed an explicit method to regenerate the local files. 
- So adding a new button in the add-on's UI doesn't seem to be required. 
- This means, our cron job to regenerate them is doing pretty well for now. Or customers are not aware of any potential issues, so they are not reporting them to us. 
- If we could preserve the current behavior and remove the local files when cache is cleared manually from the WordPress admin, I think that would be enough. 
- This way, if we ever encounter an issue, we would have a way to "cure" it at least temporarily and then we could think of a different approach at that time.

**Comment by GeekPress** [comment]
@Tabrisrp @arunbasillal If we decide to just keep the cron task, what do you think of doing it twice a week instead of once?

**Comment by arunbasillal** [comment]
@GeekPress Currently we do not have any reports or known issues where our weekly cron is causing any issue. Why fix something that ain't broken? 

Since nothing is broken, lets keep every behavior as it is?

**Comment by GeekPress** [comment]
@arunbasillal My question was more about the frequency than issue related to the cron. As we won't have a way to clear the cache ourself anymore, I was wondering about having an automatic clear twice a week instead of once. The goal will be to reduce the time to get a the last updated version.

**Comment by arunbasillal** [comment]
@GeekPress My recommendation (https://github.com/wp-media/wp-rocket/issues/2406#issuecomment-600688590) is to keep all current behavior including the ability to clear the locally stored file while the full cache is cleared manually. 

Basically preserve the current behavior. So customers will be able to flush the local files when whole cache is cleared manually. 

Don't you think that is good enough here?

**Comment by GeekPress** [comment]
@arunbasillal Let's keep the current behavior :)

**Comment by gevcen** [comment]
I'd like to say that it's not true to argue that removing Query Steing does not imorove performance. I just made a test on my site because I am ewpecting that you will release this change and it will obviously have impact on my eCommerce. Here is a test with the feature enabled and disabled.

![Screenshot_20200412-115240_Chrome](https://user-images.githubusercontent.com/51261962/79065968-7d844780-7cb4-11ea-97dd-dc47aa551020.jpg)

I understand that GTmetrix has removed this from their analysis but, it does have impact on other things on the site. Please keep the feature as it is, I dont understand why you absolutely want to remove it. You're not losing anything... you will only make it a headache for some users to get the feature with another tool which will obviously cause a lot of problems of compatibility...

Please reconsider this choice.

**Comment by GeekPress** [comment]
Hi @gevcen 

I can confirm you at 1,000,000% that Remove Query String doesn't have any impact on your loading time.

Your tests aren't good.

Why I'm saying that?
You don't have the same page size, and HTTP requests. The Remove Query String option doesn't reduce the page size or reduce HTTP requests.

Then, what's happen? You just didn't get the cached version during the second test. Be sure to make 2 or 3 tests to get an average.

Best

**Comment by 4183r** [comment]
Hello Just want to confirm after removing this function it actually slows down the website as it bypasses the CDN cache 
![image](https://user-images.githubusercontent.com/39749258/86455176-dd334180-bd3d-11ea-932f-ddfc653a908f.png)

**Comment by 4183r** [comment]
results by @gevcen are accurate, and it does impact the loading time. please reconsider adding this function again.

**Comment by arunbasillal** [comment]
@4183r Thanks for this feedback.

For Cloudflare, there is a setting to Ignore the Query string. You can find it in the `Caching` tab. See this please: 
![image](https://user-images.githubusercontent.com/5751474/86458702-4f5a5500-bd43-11ea-8444-204e9e298882.png)

That should help. Most browsers cache content regardless of the query string. And many CDN's follow suit.

**Comment by arunbasillal** [comment]
@GeekPress What do you think about making this as part of our `Optimal Settings` feature of the Cloudflare addon? https://github.com/wp-media/wp-rocket/issues/2406#issuecomment-653467657 (Thanks Piotr for the idea)

Not sure if we can do this anymore. But if we can "remember" if the user already had `Remove Query Strings` enabled in WP Rocket, then this would make total sense to automatically enable it in Cloudflare via the API

If we cannot "remember" that and if we already deleted that setting from the database, we could do not change anything for existing customers and implement this only when they re-enable `Optimal Settings`.

**Comment by GeekPress** [comment]
@arunbasillal Yes we could auto-set the caching level to « Ignore Query String ». Can you create a new issue about that enhancement?

**Comment by arunbasillal** [comment]
@GeekPress I was preparing the issue for this idea and it looks like we already do this. 

- When Optimal Settings is activated, we `Set Caching Level to "Standard"`.
- As per Cloudflare doc: 
![image](https://user-images.githubusercontent.com/5751474/86904746-c40c0580-c12e-11ea-8d2d-e19c0e39654b.png)

So we are already doing this and that is good enough. 🚀 💃

**Comment by 4183r** [comment]
I can confirm it still bypass the CDN Cache even if you put it to standard or Ignore Query String (it takes 3-4 times for the request to get a cache in CDN otherwise it just the cache status as Miss/Dynamic) and thus increating the loading time.

**Comment by arunbasillal** [comment]
@4183r Thanks for the feedback. That sounds like a weird thing with Cloudflare, doesn't seem to do what the option says. Can you please check with their support and confirm why this happens?
