### ISSUE TITLE
Remove Query Strings Option Removal: Common part (6/8)

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2435]
Sub-card for the epic #2406

This is for common files between front and admin.

###Tasks
#### inc/classes/subscriber/Tools/class-cache-dir-size-check-subscriber.php
- [x] Write tests for `cache_dir_size_check()`
- [x] `cache_dir_size_check()` method: remove check for the busting folder
#### inc/common/purge.php
- [ ] Write tests for `do_admin_post_rocket_purge_cache()`
- [x] `do_admin_post_rocket_purge_cache()` function: remove call to `rocket_clean_cache_busting()`
#### inc/functions/files.php
- [x] Deprecate the `rocket_clean_cache_busting()` function
#### inc/functions/formatting.php
- [x] Deprecate `rocket_get_cache_busting_paths()`

**Comment by Screenfeed** [comment]
@hellofromtonya Since you are writing tests for `purge.php`, should I still write the ones for `do_admin_post_rocket_purge_cache()` in #2435?
_Side note: I already wrote some short tests for the new hook introduced by #2497 [here](https://github.com/wp-media/wp-rocket/pull/2477/files#diff-c4f2162d04091834a73eb8cb2829c2bc)._

**Comment by hellofromtonya** [comment]
@Screenfeed Will there be changes to `do_admin_post_rocket_purge_cache()`?

**Comment by Screenfeed** [comment]
@hellofromtonya Yes in both cases:
- [#2494](https://github.com/wp-media/wp-rocket/pull/2494/files#diff-f26b6cf94e9197f8c8ef5da470348bbaL454) removes the call to `rocket_clean_cache_busting()`.
- [#2477](https://github.com/wp-media/wp-rocket/pull/2477/files#diff-f26b6cf94e9197f8c8ef5da470348bbaR421) adds a `do_action( 'rocket_purge_cache' )` (and a few `return;` to make it testable).

**Comment by hellofromtonya** [comment]
@Screenfeed Yes, tests are needed for the changes. Let's collaborate when you get to the tests to coordinate our work.

**Comment by Screenfeed** [comment]
Integration tests cannot be done for `Cache_Dir_Size_Check_Subscriber->cache_dir_size_check()` since it uses `->get_dir_size()`, which uses `RecursiveDirectoryIterator` instead of WP Rocket’s filesystem.
