### ISSUE TITLE
Remove Query Strings Option Removal: Facebook & Google Tracking Add-Ons part (3/8)

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2438]
Sub-card for the epic #2406

This is for Facebook & Google Tracking Add-Ons.

#### inc/common/purge.php
- [x] Add a new action hook `rocket_purge_cache` in `do_admin_post_rocket_purge_cache()`
- [x] Write tests
#### inc/classes/subscriber/class-facebook-tracking-cache-busting-subscriber.php
- [x] Replace `after_rocket_clean_cache_busting` action by `rocket_purge_cache` action for callback `delete_cache()`
- [ ] ~~Add callback method to display a notice if the busting folder for Facebook tracking files is not writable~~
- [x] Write tests
#### inc/classes/subscriber/class-google-tracking-cache-busting-subscriber.php
- [x] Replace `after_rocket_clean_cache_busting` action by `rocket_purge_cache` action for callback `delete_tracking_cache()`
- [ ] ~~Add callback method to display a notice if the busting folder for Google tracking files is not writable~~
- [x] Write tests

**Comment by Tabrisrp** [comment]
@GeekPress @arunbasillal @hellofromtonya Tagging you on this one for discussion.

With the deprecation of `rocket_clean_cache_busting()`, the two add-ons will need an update, because the deletion of their local cache files is performed by methods hooked on the `after_rocket_clean_cache_busting` action.

This brings multiple questions:
- Do we want to preserve the deletion action for those files when someone clicks on "purge cache" in the admin?
- If yes, we can add a new `do_action( 'rocket_clean_busting_files' );` wherever needed to preserve the behaviour
- If no, which alternative do we want to provide? An idea is to add a purge files button on the add-ons section, for each of them, when the add-on is enabled

**Note**: the local cache files will be deleted automatically by a cron task every 7 days in any case.

**Comment by arunbasillal** [comment]
The previous question from @Tabrisrp is being discussed in the discussion following here: https://github.com/wp-media/wp-rocket/issues/2406#issuecomment-599620046
