### ISSUE TITLE
CPCSS for specific pages: AJAX handlers (5/6)

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2444]
Sub-Card for epic #2377.

This card is for tasks related to the AJAX handlers on  the `edit.php` screen to send the requests and receive the responses + display the success/error messages.

### Tasks
- [x] Enqueue new JS file on the `edit.php` screen. Needs to be compatible with both the classic editor and the block editor
#### Generation
- [x] Send POST request to REST API endpoint, with the ID of the page and the post type as a parameter + nonce
- [x] Receive JSON-formatted response from the endpoint `{success:true|false,message:"response"}`
- [x] Display success/error message depending on the response
#### Deletion
- [x] Send DELETE request to REST API endpoint, with the ID of the page and the post type as a parameter + nonce
- [x] Receive JSON-formatted response from the endpoint `{success:true|false,message:"response"}`
- [x] Display success/error message depending on the response
