### ISSUE TITLE
CPCSS for specific pages: REST API generation endpoint (2/6)

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2445]
Sub-Card for epic #2377.

This card is for tasks related to the REST API generation endpoint.

### Tasks
- [x] Create new REST API route for POST request
- [x] Send generation request to the CPCSS generator with the post URL
- [x] Receive the response
- [x] If error, return JSON-formatted error
- [x] If success, save the generated CPCSS as a file, following the pattern `post-type-ID.css` in the `cache/critical-css/unique` folder and return JSON-formatted success
- [x] Write unit tests
- [x] Write integration tests
