### ISSUE TITLE
CPCSS for specific pages: REST API deletion endpoint (3/6)

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2446]
Sub-Card for epic #2377.

This card is for tasks related to the REST API deletion endpoint.

### Tasks
- [x] Create new REST API route for DELETE request
- [x] Try to delete existing CPCSS file following the pattern `post-type-ID.css` in the `cache/critical-css/unique` folder
- [x] Receive the response
- [x] If error, return JSON-formatted error
- [x] If success, return JSON-formatted success
- [x] Write unit tests
- [x] Write integration tests
