### ISSUE TITLE
Preload counter not incrementing

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2454]
**Describe the bug**
In specific cases, the preload counter is not incrementing. There are two separate things that are happening to the customer and they're causing the preload to stuck.

The first one is related to this `If` statement:
https://github.com/wp-media/wp-rocket/blob/8b2a567efcab3925dba6fff72c5a622ec2d16386/inc/Engine/Preload/FullProcess.php#L46
If `$item` is a string, we're not passing it. It means that the URLs are preloaded but the counter is not updated.

**To Reproduce**
1. Using an environment where `$item` is a string
2. Preload the cache
3. Confirm that the counter is not updated

**Expected behavior**
The counter should be updated.

**Additional context**
I used the code provided by Greg to check if it solves the issue:
http://snippi.com/s/fpmu2v6

The transient here was updated correctly then:
https://github.com/wp-media/wp-rocket/blob/8b2a567efcab3925dba6fff72c5a622ec2d16386/inc/Engine/Preload/FullProcess.php#L49

Unfortunately, the UI wasn't updated as the results weren't correct here:
https://github.com/wp-media/wp-rocket/blob/9b175725a5c568f27808875c041fc67cba264ae7/inc/Engine/Preload/PreloadSubscriber.php#L273-L274

I'm waiting to confirm that the Object Caching is not enabled in this environment.

Affected environment:
https://secure.helpscout.net/conversation/1107778087/151265?folderId=2415573

**Backlog Grooming**
- [ ] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Screenfeed** [comment]
**Reproduce the problem** ❌
I couldn't find any places where items are pushed to the queue as strings instead of arrays.

**Identify the root cause** ✅
I see two possible causes:
- Third party code: the user has a third-party plugin that pushes items to the queue as strings.
- Queue built prior update: the queue may have been built with the previous version of WP Rocket, as strings. Then the new system, requiring arrays, processes this queue. This is most probably what happened.

**Scope a solution** ✅
Several solutions, that can potentially be implemented together when possible:
1. Continue to allow strings for backward compatibility. Consequences:
  * Since the item is a string, there is no way to identify its source (`homepage`, `sitemap`), it leads to a transient name `rocket__preload_running`. We could either set the source as an empty string (and keep this transient name), or set it to a default `unknown` value: `rocket_unknown_preload_running`. Then we use this 3rd transient in the admin notice displaying the number of URLs being preloaded so far. Pros: simple to implement. Cons: more requests to the database.
2. Same as *1.* but use a direct database request to fetch all transients as once (`option_name LIKE 'rocket_%_preload_running'`). Pros: less calls to the database, nothing to change if someday we add more sources. Cons: must handle object caching, which doesn't seem a big deal.
3. Forbid strings, allow only arrays: items as strings are silently discarded. Type hinting may not be a good idea here.
4. Delete preload queues on upgrade with a direct call to the database.

**Estimate the effort** ✅
effort: `[S]` to `[M]`

Personally I would go for *2.* + *4.*.

**Comment by camilamadronero** [comment]
New case at https://secure.helpscout.net/conversation/1106894623/150945/.

**Comment by jazir5** [comment]
I have this issue as well, where the preload count is not accurately reported. Specifically, the preload counter will show that the preload process has completed, when it definitely should not yet be. The notification status will change to something like "6 pages preloaded" with the green confirmation check that preload has completed, but my site has over 60 pages which should be preloaded.

Sometimes it doesn't seem to initiate preload at all when i hit preload, or the preload status will get stuck at a certain number(page 5/65) for instance, and refuses to let me cancel the preload or increment the preload counter higher.

**Comment by hellofromtonya** [comment]
We need to find the **_root cause_** of why a non-array is being sent to `task( $Item )` _**before**_ we can design a solution for it. Else, the Preload counter will continue to not increment correctly. 

@crystinutzaa @Screenfeed Let's focus on reproducing the problem and finding the root cause. We have a couple of customers who have this specific problem. @piotrbak can we get access to do some analysis and testing on the customers' sites?

**Comment by crystinutzaa** [comment]
**Identify the root cause** ❌ 
@piotrbak asked the customer to provide access on 29April, however it seems that the client did not reply. He saw the email, but there is no reply.
I assume in this situation that he will not send us access so we can recheck this issue.
This makes things harder to identify why this happens.

**Scope a solution** ❌ 
The solution will be in the new Preload system. 
The new Preload system will keep in a database all URLs of the website with a timestamp when the cache was last time generated. So based on the timestamp we can decide if the page is already preloaded or needs to be preloaded (cache expired).
So, the Preload counter should be accurate because will be fetched from the database and will not rely anymore on transients which are saved and updated.

**Effort** ❌ 
Not known yet.

**Milestone** ❌ 
This should be added to v3.7 when the new Preload system will be implemented.

**Comment by hellofromtonya** [comment]
This issue will be fixed in 3.7. It's blocked until the new Preload module is built.

**Comment by hellofromtonya** [comment]
This issue will be fixed in a future major release. It's blocked until the new Preload is built.

**Comment by piotrbak** [comment]
The issue is not relevant with the 3.12 preload implementation.
