### ISSUE TITLE
After editing a post with a Elementor, Divi or Beaverbuilder, the post cache gets deleted but not preloaded

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2553]
**Before submitting an issue please check that you’ve completed the following steps:**
- Tested with WP Rocket 3.5.2, Elementor 2.9.7, Beaverbuilder Version 2.3.2.5 and Divi 4.3.2. 

**Describe the bug**
When saving a post using the one of these editors, the post cache and its related contents are cleared but not preloaded again.

**To Reproduce**
1. If using Elementor, set _Settings_ -> _Advanced_ -> **CSS Print Method** to **Internal Embedding**, because we are clearing the full cache if this option is set to External File. 
2. Check WP Rocket preload is enabled. 
3. Edit a post/page with Elementor editor: https://jmp.sh/6GMiNbF
4. Click on Save: https://jmp.sh/In4NCav
5. Check the cache folder for that post/page and site index using FTP
6.  The post cache and home page is deleted but is not preloaded after an edit
7. Run the same test with the default WordPress editor. 
8. Check the FTP folder, the cache will be cleared and preloaded

**Expected behavior**
The page and the homepage should be preloaded after it is updated. 
As it happens when using the default WordPress Editor

**Videos**
This is the behavior when using the regular WordPress Editor: 
https://jmp.sh/YcQ2ntF

And this is what happens when using Elementor, for example: 
https://jmp.sh/E0xP6fQ

**Additional context**
With the help of Piotr Boniu, we've traced this in different parts of our code. We've found that for Elementor, DIVI and (probably) BeaverBuilder, the preloading process is stopped here:
https://github.com/wp-media/wp-rocket/blob/00cf7a1c5e0b2e7354b0aa76ca86603ee4420eae/inc/Engine/Preload/PartialPreloadSubscriber.php#L185-L187

It seems that the `wp_doing_ajax` is true and the return takes place.
When commenting that line, the post preload works ask expected.

Tested using DIVI: 
https://jumpshare.com/v/044NE0fNEAIODR7c4E5e

When testing using BeaverBuilder, the results are not very consistent, sometimes the cache gets deleted and recreated as expected, and sometimes the cache regeneration doesn’t work at all. 

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jazir5** [comment]
Can confirm the same on my end

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1120402546/153953/

**Comment by piotrbak** [comment]
Related:
https://secure.helpscout.net/conversation/1146831025/160692/

**Comment by mifrero** [comment]
Related ticket:
https://secure.helpscout.net/conversation/1159070192/163754/

**Comment by crystinutzaa** [comment]
**Identify the root cause** ✅ 
The root cause is indeed at wp_doing_ajax in here.
https://github.com/wp-media/wp-rocket/blob/00cf7a1c5e0b2e7354b0aa76ca86603ee4420eae/inc/Engine/Preload/PartialPreloadSubscriber.php#L185-L187

It seems that the `wp_doing_ajax` is true and the return takes place.

**Scope a solution** ❌ 
The solution will be in the new Preload system. Basically the new Preload system will identify if a post was updated / changed / deleted and simply update the info in the cache_preload database table. 
The new Preload system will never rely on `wp_doing_ajax` because will simply update the database field.

**Effort** ❌ 
Not known yet.


**Milestone** ❌ 
This should be added to v3.7 when the new Preload system will be implemented.

**Comment by hellofromtonya** [comment]
This issue will be fixed in a future major release. It's blocked until the new Preload is built.

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1330713824/209655?folderId=2135277

**Comment by piotrbak** [comment]
It's fixed with the new preload.
