### ISSUE TITLE
Move RocketCDN module to new repo

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2675]
This user story is part of a dev initiative.

- [x] Create a new repo
- [x] Move the RocketCDN module to it
- [x] Move its unit tests, integration tests, and test data fixtures to the new repo

Benefits:

- Reduces impact on our CI - less static analyzers and tests has to run on Rocket
- Encapsulation
- Maintainability
