### ISSUE TITLE
Create Filesystem Module

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2676]
This user story is part of a dev initiative.

- [ ] Create a new repo
- [ ] Complete full test coverage for existing filesystem functions
- [ ] Move functionality into Filesystem module
- [ ] Move functions to API and wire to Filesystem module
- [ ] Inject filesystem module into other classes that use it
- [ ] Move its unit tests, integration tests, and test data fixtures to the new Filesystem module repo
