### ISSUE TITLE
Move CriticalPath module to new repo

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2677]
This user story is part of a dev initiative.

- [ ] Create a new repo
- [ ] Move the CriticalPath module to it
- [ ] Move its unit tests, integration tests, and test data fixtures to the new repo

Benefits:

- Reduces impact on our CI - less static analyzers and tests has to run on Rocket
- Encapsulation
- Maintainability
