### ISSUE TITLE
New Preload Module

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2678]
We will be redesigning the Preload feature into a new module. This user story captures our initial discussions about architecture, queues, elastic background workers, and more. 

The goals:

- [x] Fix all existing issues
- [x] Transform Preload into a scalable, robust, reliable, and performant feature

**Comment by hellofromtonya** [comment]
## Sprint 7 TODOs

- [ ] Identify all known issues
- [ ] Debate, discuss, and agree on how we will build the new module
- [ ] Map/diagram an architecture
- [ ] Identify high risk areas
- [ ] Prototype those areas
- [ ] Breakdown the epic into smaller sub-tasks (user stories)

**Comment by hellofromtonya** [comment]
We are postponing this epic for a future major release.

**Comment by crystinutzaa** [comment]
### 1. Database module 
- Use the prototype created in https://github.com/wp-media/module-db and extend it:
### 1.1 Schema - use Innodb tables at schema creation
    - [S] - Move the creation of the tables out of AdminServiceProvider.php 
    - [S] - Alter the current code in Schema to allow a single DB table creation at a time (even if multiple tables can be created). The prototype which I created allows an array of DB tables to be passed. In fact it should pass a single DB table creation at a time. 
    - [M] - Create DbUpgrade system for schema with upgrade() & undo() methods. The upgrade system will contain an array with ALTER table statements.Upgrade system tracks and allows users to upgrade from older versions and apply all schema changes. The upgrade sistem will need a controller which will handle the running of all the upgrade files and the direction: upgrade() or undo().
### 1.2 Base Model
    - [S] - Add data validation based $definition -> type & validate & required field
    - [S] - SQL injection - revisit all code to prevent SQL injection
    - [S] - Make the prototype function calls to DB selects more generic.


### 2. Cache module 
- Refactor the code in `classes/Buffer` into new structure and also accomodate the DB Cache table.
### 2.1 Create a new folder in /inc/Engine/Buffer/Database which will handle the Cache DB Object model.
    - [S] - Move all files from module-db/cache folder in this folder.
### 2.2. `classes/Buffer` refactor
    - [S] - Cache module will rely on Cache DB table to check if the cache needs to be created or not for the current page
    - [S] - Add a filter into class_cache -> can_process_buffer() which will trigger the Cac0.he DB table update / insert - `rocket_cache_db` and will send the URL, PATH & USER_ID (0 if no user)
    - [S] - inc\classes\Buffer\class-abstract-buffer.php - refactor + code improvement
    - [S] - inc\classes\Buffer\class-cache.php - refactor + code improvement
    - [S] - inc\classes\Buffer\class-config.php - refactor + code improvement
    - [S] -  inc\classes\Buffer\class-optimization.php - refactor + code improvement
    - [S] - inc\classes\Buffer\class-tests.php - refactor + code improvement 
    - [S] - Deprecate all code in /inc/classes/Buffer
    - [S] -Revisit files which use /inc/classes/Buffer 
                      -  \views\cache\advanced-cache.php
                      -  \inc\functions\htaccess.php
                      -  \inc\Engine\Optimization\ServiceProvider.php
                      -  \inc\deprecated\3.6.php
                      -  \inc\deprecated\3.3.php
                      -  \inc\classes\subscriber\Optimization\class-buffer-subscriber.php
                      -  \inc\classes\Cache\class-expired-cache-purge.php

### 3. Expired Cache Purge
- ExpiredCachePurge (class & Subscriber) refactor and move the code into the structure & modify the code to use the DB table for purging instead of relying on files.

    - [S] - WP_Rocket\Cache\Expired_Cache_Purge
    - [S] - WP_Rocket\Subscriber\Cache\Expired_Cache_Purge_Subscriber
    - [S] -  \inc\Plugin.php - revisit common subscriber and remove expired_cache_purge_subscriber
    - [S] - \inc\classes\ServiceProvider\class-common-subscribers.php - revisit and remove expired_cache_purge & _subscriber
    - [M] - Write Full Code coverage tests & Revisit current tests (unit & integration)

### 4. Preload Module
- Preload module changes
     ### 4.1 Deprecate all files under Preload folder
    - [S] - Deprecate all files under Preload folder and remove all tests related to the current preload system.

     ### 4.2 CACHE WARMUP
    - [M] - Create a new class which will be responsible for populating the Cache DB table. This will have a Button in Admin: Cache Warmup which will delete the full db cache table (or merge the current values with the new values identified). Clicking on the button the warmup functionality will either check the sitemaps or will create a crawler which will grab the URLs and add those in DB cache table.

     ### 4.3 SYNC Files
    - [M] -this is needed in case someone deletes the full cache directory to invalidate full DB cache and start preloading
    - We can end up in the situation when the customer manually deleted all files in /wp-content/cache/wp-rocket and our DB table is out of sync. 
    - In this situation I think we need to have a functionality which will check and sync the files with our DB table.
    - I think we shall use a scheduled event which will check on a regular basis (each 12 hour / hourly / once a day) if the cache files exist in the DB. If the files do not exist it will update the missing files (either set it to expired or delete totally the row from the DB)

     ### 4.4 New Preload
    - [M] - The new functionality will not allow for Full Preload and Partial Preload. The new functionality will be a continuous preload based on the DB cache table.
    - Create a new class Preload.php which will take care of preloading a single URL based on the Cache Row table. This class will preload both desktop and mobile version of the URL if this option is enabled.
    - Create a new controller PreloadController.php which will take care on preloading a batch of URLs (function preload_heartbeat()) - The controller will grab from the Cache DB the next 10 -20 - X cache files which are expired and Preload those. 
    - Create a new Subscriber for Preload which will implement the preload_heartbeat() and will enqueue the preload heartbeat JS script.
    - The Preload will work with a heartbeat exactly as CriticalPath.
    - Create a JS file which will run in Backoffice exactly as: `\assets\js\wpr-cpcss-heartbeat.js` with an AJAX call `rocket_preload_heartbeat`.


### 5. [M] Third party connections
- https://docs.google.com/document/d/1DteuvWytTewVGvy480XC7cGKuYwpp7jRfLat3k5W5NA/edit?usp=sharing
The Cache DB needs to be updated in certain situations specified in the previous document. This will trigger 3 different calls:
    - Invalidate full cache - meaning that all DB tables should set the expiry date in the past. I created in DB Module a new function which will set all db table rows expiry column to NOW() - 1 hour ( so the cache is expired)
    - https://github.com/wp-media/module-db/blob/8dace413f31b258f00db96f750d4b446c2b733a1/Cache/Model.php#L129-L131
    - Invalidate Partial Cache - send an array of Paths (paths will be unique in the DB table and not URLs) for which the expiry date needs to be set in the past
    - Delete a row in the Cache DB in case a post / page is totally deleted.

**Comment by jazir555** [comment]
Why has all work seemingly stopped on this feature? Preload is supposedly a major feature of the plugin, and it's pretty much non-functional as it is.

**Comment by Michaelgimii** [comment]
Does preloading images include this feature?
