### ISSUE TITLE
Completing and Readying 3.6 for release

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2679]
This user story captures the tasks needed to complete and ready 3.6 for release:

## TASKS

- [x] Finish 3.6 user stories, issues, and epics:
    - [x] Gzip compression for static files #2465
    - [x] Get rid of the Remove Query Strings option #2406
    - [x] CPCSS for Specific Pages #2377
    - [x] CPCSS for Mobile #2378
    - [x] Expired cache preload doesn't fetch the correct URLs #2665
    - [x] Include `<a>` tags when applying LazyLoad to background images #2660
    - [x] Hide RocketCDN when white label is enabled #2671
    - [x] Re-enable lazyload updates #2680
    - [x] Move `class-plugin.php` into new architecture #2656

- [x] Merge all feature and fix branches into `develop`. Fix any merge conflicts.

- [x] Live test `develop` as a completed package

- [x] Release notes:
     - [x] Create release notes for Product to review
     - [x] @arunbasillal to review and improve

- [x] Do internal alpha release
    - [x] Alpha release without CPCSS for mobile

- [x] Write up 3.6 feature articles like we did for 3.5: 
     - what changed
     - add a demo
     - Support tips
     - code changes

 - [x] Do staggered release

## Feature posts
- [x] CPCSS for specific posts
- [x] CPCSS for mobile
- [x] Preload fonts (Remy)
- [x] Serve pre-compressed gzip files (Remy)
- [x] Other misc changes

**Comment by hellofromtonya** [comment]
@Tabrisrp Do you think we should include this in 3.6 release? https://github.com/wp-media/wp-rocket/pull/2656

**Comment by Tabrisrp** [comment]
If we can finish it in the next days, yes, it's a welcome improvement

**Comment by hellofromtonya** [comment]
@Tabrisrp Once we merge in CPCSS for Mobile, then I can update this one with the new changes. Let's plan to include this PR in 3.6. 🎉

**Comment by Tabrisrp** [comment]
Changelog document: https://docs.google.com/document/d/1f43kYloLTCLe5Pea_SzIjk5clDTwLCkBrk3qpDnan98/edit?usp=sharing
