### ISSUE TITLE
Htaccess-related code refactor

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2759]
### Development
Refactor our `htaccess` related code to improve performance of how we process and update the content of the `.htaccess` file.

#### Part1 - Fixing the current issue
Change `"access plus 1 month"` to ` "access plus 4 months"`
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/functions/htaccess.php#L475-L478

#### Part2 - Move htaccess to new code architecture `inc/Engine/Htaccess/Htaccess.php`
- [ ] Inject Options_Data as a dependency
- [ ]  deprecate all functions from `htaccess.php`
- [ ] Create a new method `regenerate_htaccess()` method to update the file (replaces `flush_rocket_htaccess()`)
- [ ] Move each function for the different rules blocks here, update them to reduce complexity. Use views/templates for each rules block instead of having them hardcoded in the  methods code. Read from those files to replace placeholders and return the block.
-  [ ]  Add a new method maybe_regenerate_htaccess() that will check for wp_cache_get( 'rocket_flush_htaccess' ), and if it’s set, call regenerate_htaccess() + wp_cache_delete( ‘rocket_flush_htaccess’ )

#### Part3 -  Create a new class `inc/Engine/Htaccess/Subscriber.php`
- [ ]  Inject `Htaccess` class as a dependency
- [ ]  Callback on admin_notices with notice_warning_htaccess_permissions()
- [ ]  Callback on shutdown with maybe_regenerate_htaccess()
- [ ] Deprecate function rocket_warning_htaccess_permissions() and remove it from notices.php

#### Part4 - `flush_rocket_htaccess()`
- [ ]  Move flush_rocket_htaccess()  in `inc/functions/api.php`, and update its code to use the Htaccess class method to perform the file update
- [ ] Replace calls of `flush_rocket_htaccess()` everywhere in the plugin by `wp_cache_set( 'rocket_flush_htaccess' )`

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/functions/htaccess.php#L475-L478

**Scope a solution** ✅ 
Change `"access plus 1 month"` to ` "access plus 4 months"`
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/functions/htaccess.php#L475-L478

**Effort** ✅ 
Needs discussion

**Comment by hellofromtonya** [comment]
Update:
In talking with the engineering team, we have an opportunity to properly fix the issue AND improve the performance (memory and processing) of how we process and update the `.htaccess` file from within the code itself. The team is collaborating together on the tasks and effort. Once done, we'll come back and add the details for sprint planning.

**Comment by GeekPress** [comment]
@hellofromtonya Can we split this in two different tasks?

1. This card to fix the current issue
2. A new card for the .htaccess rewrite strategy.

Why?
This issue could be fixed easily and very fast. It could avoid tickets on support side.

If we do the fix at the same time of the rewrite, the fix won't be available until 3.7 as this kind of rewrite should be released and scheduled for a major version.

**Comment by crystinutzaa** [comment]
## **Development**

## Part1 - Fixing the current issue
Change `"access plus 1 month"` to ` "access plus 4 months"`
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/functions/htaccess.php#L475-L478

## Part2 - Move htaccess to new code architecture `inc/Engine/Htaccess/Htaccess.php`
-  [ ] Inject Options_Data as a dependency
-  [ ]  deprecate all functions from `htaccess.php`

## Part3 -  Refactor  `flush_rocket_htaccess()` with reduced complexity
-  [ ] Create a new method `regenerate_htaccess()` method to update the file. Mainly based on `flush_rocket_htaccess()` with reduced complexity & remove this function.

## Part4 -  Add a new method  `maybe_regenerate_htaccess()` 
-  [ ]  Add a new method maybe_regenerate_htaccess() that will check for wp_cache_get( 'rocket_flush_htaccess' ), and if it’s set, call regenerate_htaccess() + wp_cache_delete( ‘rocket_flush_htaccess’ )
Move each function for the different rules block here, update them to reduce complexity

## Part5 -  Refactor code to use views/templates for each rules block
-  [ ]  use views/templates for each rules block instead of having them hardcoded in the  methods code. Read from those files to replace placeholders and return the block.

## Part6 -  Create a new class `inc/Engine/Htaccess/Subscriber.php`
-  [ ]  Inject Htaccess class as a dependency
-  [ ]  Callback on admin_notices with notice_warning_htaccess_permissions()
-  [ ]  Callback on shutdown with maybe_regenerate_htaccess()
-  [ ] Deprecate function rocket_warning_htaccess_permissions() and remove it from notices.php


## Part7 - Move `flush_rocket_htaccess()` into `inc/functions/api.php`
-  [ ]  Move flush_rocket_htaccess() here, and update its code to use the Htaccess class method to perform the file update

## Part8 - Third party calls to `flush_rocket_htaccess()`
-  [ ] Replace calls of flush_rocket_htaccess() everywhere in the plugin by wp_cache_set( 'rocket_flush_htaccess' )


@Tabrisrp & @hellofromtonya can you take a look how I splitted it? For tests, where and how should I specify it in each sub-task epic?

**Comment by piotrbak** [comment]
Thi is not going to be implemented in the nearest future
