### ISSUE TITLE
3.6.3 Release Checklist

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2858]
This card identifies all of the tasks that need to be completed for the minor release. Each task owner is responsible to communicate in this card about status and check when done and ready.

These tasks need to be completed _before_ we can proceed with the 3.6.3 release:

Tasks belonging to the Dev Scrum Team @wp-media/php:

- [x] Merge all PRs for this minor release.
- [x] Close all issue cards that will ship in this minor release.
- [x] Identify any non-merged items that are needed for this minor release (comment below).
   -  [x] Get all of them completed, through QA, and merged.
- [x] Do final QA on the completed release branch (one last check to ensure everything works as expected when merged together). @wp-media/qa 
- [x] Release any dependencies, such as Lazy Load Common library or other modules/libraries.
- [x] Create the changelog and review with @arunbasillal.
- [x] Create draft feature documents in Notion, if applicable.
- [x] Create the translations/transifex.

Tasks belonging to others:

- [x] Notify Daniella. Owned by @hellofromtonya @arunbasillal @GeekPress 
- [x] Notify Agathe. Owned by @hellofromtonya @arunbasillal @GeekPress 
- [x] Finish documentation. Owned by @webtrainingwheels
- [x] Support is ready. Owned by @DaniJacome 
- [x] Product approves the release. Owned by @arunbasillal  or @GeekPress
