### ISSUE TITLE
Preload pages before the user click on it

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2898]
## What are we proposing to do? 

With this feature, WP Rocket will preload a link before the user is ready to click on it. Initially we will be preloading as soon as the user hovers over a link that they are about to click. In the future we can iterate to be smarter about this. 

<p></p>

An example of a similar feature is available here: [<u>https://instant.page</u>](https://instant.page)

## Why are we doing this?

Before clicking on a link, a user hovers over the link for a fraction of a second. If we start preloading the page at this moment, that is time saved from the actual rendering of the page. This can result in a perceived performance gain and provide a better user experience. 

## User expectations and experience. How will we do this feature?

Users will enable this feature via a UI option in the “Preload” tab of WP Rocket. Everything else will be handled by WP Rocket automatically without further user input. 

<p></p>

**UI Proposal**

![](https://lh3.googleusercontent.com/PfzvZ3UVFa9FzHquMnuBd2Dwx6K6x67GJtnXdVIYswMQpgrPUKAoyFIAH7RSRd0a6xJy77d4OzjKlCy2Kcx-LvftdJh9uZ5l0wE7HjvSFlHKfMz35q5Vzd5Zb1RBBaWt9sZGiXPE)

<p></p>

Location: “Preload” tab. **After “Preload Fonts”.** 

Section Title: **Preload Links**

Option Description: **Link preloading improves the perceived load time by downloading a page when a user hovers over the link. More info**

Option Name: **Enable link preloading**

## Technical Specs

A comparison of existing solutions is available here: [<u>https://wpspeedmatters.com/quicklink-vs-instant-page-vs-flying-pages/</u>](https://wpspeedmatters.com/quicklink-vs-instant-page-vs-flying-pages/)

<p></p>

Some feature recommendations that I think are useful: 

- Preload only HTML, not the images or other assets. 

- Do not preload if the mouse just passes over the link. If the user scrolls over a menu, that will be a lot of preloaded links. 

- Limit the number of preloads per second. This will also help with the previous situation where the user scrolls over a bunch of links. 

- Disable the feature if the browser uses data saver mode. Instant page does this. 

## Risks

- Since the feature has to be manually enabled, there is no risk during the introduction of the feature. 

- Potential issues are of high CPU usage, but we can improve on this as we see such cases. In the meantime, such users can disable the feature. 

## Acceptance Criteria

- Enable the option. Hover over a link and the page will start preloading. 

- Simply moving the mouse swiftly over the link shouldn’t start the preloading. 

- On a mobile device, preloading starts when the user touches the link before releasing it. Can be tested via console on browser stack.   

**Testing notes:** 

- Cross browser testing is recommended for this to make sure we don’t break things on different browsers. 

## Documentation and Translations

- Create new documentation to describe this feature and it’s benefits.

**Comment by GeekPress** [comment]
Link to feature: https://wp-media.productboard.com/feature-board/planning/features/4224267

**Comment by GeekPress** [comment]
**Additional infos**

1.
These plugins needs to be added into our conflicted plugins list when the preload link option is turned on:

- [Flying Pages](https://wordpress.org/plugins/flying-pages/)
- [Instant.page](https://wordpress.org/plugins/instant-page/)
- [Quicklink](https://wordpress.org/plugins/quicklink/)

2. The JS will be developed by @hellofromtonya

**Comment by Tabrisrp** [comment]
In which situation(s) the script should not be added if the option is enabled, if any? Should we insert it all the time, or prevent it when user is logged-in with no user cache, excluded pages, etc? It could be good to have the full details on this.

**Comment by GeekPress** [comment]
@Tabrisrp The script shouldn't be added when a page is excluded from the cache. In that way, it will be compatible with cart and checkout page on e-commerce websites.

**Comment by hellofromtonya** [comment]
@GeekPress @arunbasillal @Tabrisrp Noting here for reference:

Safari and iOS Safari browsers do not support `link rel="prefetch"`.  [See caniuse.com for more info](https://caniuse.com/#feat=link-rel-prefetch).

**Comment by GeekPress** [comment]
Ping @webtrainingwheels for the documentation👆

**Comment by Tabrisrp** [comment]
It can be activated for Safari from the `developer menu > experimental features`, selecting `LinkPrefetch`

**Comment by hellofromtonya** [comment]
>It can be activated for Safari from the developer menu > experimental features, selecting LinkPrefetch

I'm searching for a way to do it programmatically, i.e. turn on that feature. Not finding it. Searching....

BTW - that feature is not available in iOS Safari.

**Comment by hellofromtonya** [comment]
>The preload link script process links for logged in users[when cache for logged in users is disabled], it does not actually preload the pages but it does add the links to the head. - wondering if we can skip that since.

David found 👆 . @GeekPress @arunbasillal what are your thoughts here?

**Comment by Tabrisrp** [comment]
Even if the page is not preloaded in the sense of "no cache created", the prefetch is still a performance improvement, since it's speeding up the loading of the next page.

Talked with David about that, and we agreed it's worth keeping.

**Comment by hellofromtonya** [comment]
@GeekPress @arunbasillal @webtrainingwheels @Tabrisrp @Davidacu FYI: Edge and IE are also not compatible with this feature as they do not support link prefetch either. Bummer.

Tests ran on Edge browser:

- [x] Test 1: Fails the "supports prefetch" check in our script, meaning the browser does not support it.
- [x] Test 2: disabled that check. Results:
    - Adds the link prefetch element into the HTML. 
    - Browser does not go and fetch it. (not loaded in the Network panel)
- [x] Test 3: check still disabled. Added link prefetch element into `<head>` as part of the template. Results:
     -Nope. That didn't work either.

**Comment by hellofromtonya** [comment]
## Update to this feature for documentation

This feature will not process the following links:

- [x] Pages: `add-to-cart`, `cart`, `checkout`, `logout`, `wp-admin`, `wp-login.php`
- [x] Anchor links `#`
- [x] URLs with query string(s) `?hello` or `?product=shirt&color=blue`
- [x] URLs with protocol: `javascript:`, `mailto:` or `data:`

**Comment by hellofromtonya** [comment]
[Excellent resource on how the browser handles link prefetching on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ). 

### What is link prefetching?
>Link prefetching is a browser mechanism, which utilizes browser idle time to download or prefetch documents that the user might visit in the near future. A web page provides a set of prefetching hints to the browser, and after the browser is finished loading the page, it begins silently prefetching specified documents and stores them in its cache. When the user visits one of the prefetched documents, it can be served up quickly out of the browser's cache.

In a nutshell, the performance boost comes from the browser fetching the (partial or full) document from its cache.

## What happens if I click on a link while something is being prefetched?
>When the user clicks on a link, or initiates any kind of page load, link prefetching will stop and any prefetch hints will be discarded. If a prefetched document is partially downloaded, then the partial document will still be stored in the cache provided the server sent an "Accept-Ranges: bytes" response header. This header is typically generated by webservers when serving up static content. When the user visits a prefetched document for real, the remaining portion of the document will be fetched using a HTTP byte-range request.

A click event may happen faster than a document can be prefetched and downloaded from the server. But that's okay. Why? Assuming the connection is fast enough with the server so that the download starts, we still get performance benefits of the partial document download.
