### ISSUE TITLE
3.7 release checklist

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2979]
This card identifies all of the tasks that need to be completed for the major release. Each task owner is responsible to communicate in this card about status and check when done and ready.

These tasks need to be completed _before_ we can proceed with the 3.7 release:

Tasks belonging to the Dev Scrum Team @wp-media/php:

- [x] Merge all PRs for this major release.
- [x] Close all issue cards that will ship in this major release.
- [x] Identify any non-merged items that are needed for this major release (comment below).
   -  [x] Get all of them completed, through QA, and merged.
- [x] Do final QA on the completed release branch (one last check to ensure everything works as expected when merged together). @wp-media/qa 
- [x] Release any dependencies, such as Lazy Load Common library or other modules/libraries.
- [x] Create the changelog and review with @arunbasillal.
- [x] Create draft feature documents in Notion, if applicable.
- [x] Create the translations/transifex.

Tasks belonging to others:

- [x] Notify Daniella. Owned by @hellofromtonya @arunbasillal @GeekPress 
- [x] Notify Agathe. Owned by @hellofromtonya @arunbasillal @GeekPress 
- [x] Finish documentation. Owned by @webtrainingwheels
- [x] Support is ready. Owned by @DaniJacome 
- [x] Product approves the release. Owned by @arunbasillal  or @GeekPress

#### Delay JavaScript execution
- [x] Create feature doc on Notion (@engahmeds3ed)
- [x] Training session with level 2 (@engahmeds3ed)

#### Preload links
- [x] Create feature doc on Notion (@Tabrisrp)
- [x] Training session with level 2 (@Tabrisrp)

#### New bypass method to prevent optimizations
- [x] Create feature doc on Notion (@iCaspar)
- [x] Training session with level 2 (@iCaspar)

#### Host locally & minify 3rd party CSS & JS files when minify CSS/JS option are enabled
- [x] Create or update feature doc on Notion (@iCaspar)
- [x] Training session with level 2 (@iCaspar)

#### Automatically add font-display:swap & Combine 3rd party CSS files into the combined CSS files
- [x] Create or update feature doc on Notion (@engahmeds3ed)
- [x] Training session with level 2 (@engahmeds3ed)

**Comment by Tabrisrp** [comment]
### Changelog (draft)
- New feature: Add a new Delay JavaScript execution option, using a list of scripts URL or inline patterns to improve your loading speed (#2899)
- New feature: Add a new option to prefetch pages before the user clicks on a link to improve perceived loading speed & user experience (#2898)
- Enhancement: Host locally & minify 3rd party CSS & JS files when minify CSS/JS option are enabled (#2810)
- Enhancement: Automatically add `font-display:swap` to CSS files containing a font-face to improve rendering time (#2791)
- Enhancement: Combine 3rd party CSS files into the combined CSS files when combine CSS is enabled (#2689)
- Enhancement: The Optimize Google Fonts option is now automatically enabled & applied (#2877)
- Option removal: Remove the minify HTML option, as its impact on loading time and file size is negligible (#2682)

@arunbasillal please review it

**Comment by arunbasillal** [comment]
@Tabrisrp Few comments from the team regarding the changelog is mentioned here - https://wp-media.slack.com/archives/C016DRMRG6S/p1598469949005000?thread_ts=1598394849.009300&cid=C016DRMRG6S

Please consider them. Thank you 👍
