### ISSUE TITLE
Voxpower tracker not working properly if deferred (to be added to the automatic exclusion)

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3181]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Dependency issue with their inline script if external scripts are deferred. 

```
<script type='text/javascript' src='https://cdn.voxpow.com/static/libs/v1/voxpow.js' id='voxpow-script-js' defer></script>
<script type='text/javascript' src='https://cdn.voxpow.com/static/libs/v1/voxpow-widget.js' id='voxpow-widget-script-js' defer></script>
<script type='text/javascript' src='https://cdn.voxpow.com/media/trackers/js/vp-xxx-xxx.js' id='voxpow-tracker-script-js' defer></script>
<script type='text/javascript' id='voxpow-tracker-script-js-after'>
var voxpowShow=voxpowShowTracker();voxpow&&voxpowShow&&
            (voxpow.setLanguage(voxpowLanguage),voxpow.addCommands(voxpowCommands),
            voxpow.addCallback(voxpowCallbacks),SpeechKITT.voxpow(),
            SpeechKITT.setStylesheet(voxpowStylesheet),SpeechKITT.setInstructionsText(voxpowSearchMessage),
            SpeechKITT.setToggleLabelText(voxpowLabelText),SpeechKITT.rememberStatus(voxpowRememberStatus),
            SpeechKITT.render(),voxpowUseVoiceTyping&&document.addEventListener&&"function"==typeof
            voxpowInitTextVoice&&(document.addEventListener("DOMContentLoaded",
            voxpowInitTextVoice,!1),setInterval(voxpowInitTextVoice,1e3)));
</script>
```

**To Reproduce**
1. Add Voxpower tracking scripts 
2. Enable our JS deferring feature
3. Check the error on the console

**Expected behavior**
Excluding **cdn.voxpow.com** from deferring fixes the issue.

**Screenshots**
![Screenshot](https://i.vgy.me/jEl9u1.png)

**Additional context**
N/A

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Ticket - https://secure.helpscout.net/conversation/1299538600/199445/

**Comment by arunbasillal** [comment]
@DahmaniAdame Thanks for the report. Please [report exclusions like this directly to L2](https://www.notion.so/Assigning-tickets-to-Level-2-9e5066dc28a541419a20139fdfb8aded) so that they can be added directly as a PR. Saves you time from creating an issue and saves the dev team some time. 

I have pinged @vmanthos and he has kindly agreed to take this one 🙌
