### ISSUE TITLE
Issue when Google fonts using different APIs are combined

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3264]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Google fonts API v2 has introduced a new syntax and the main detail causing the issue on our end is that they now use semicolons to separate style instead of comas.

V1 - https://fonts.googleapis.com/css?family=Poppins:wght@100,200,300,400,500,600,700,800,900
V2 - https://fonts.googleapis.com/css2?family=Poppins:100;200;300;400;500;600;700;800;900

What happens is that if both APIs are used, our combined Google fonts is delivering the V2 fonts in a way that is not compatible with V1 (which is the one we use when delivering combined fonts).

https://fonts.googleapis.com/css?family=Lato:wght@100;300;400;700;900|Poppins:wght@100;200;300;400;500;600;700;800;900|Merriweather:400,700,900,400italic,700italic,900italic|Montserrat:400,700|Inconsolata:400&subset=latin,latin-ext&display=swap

As a result, in the combined file above, we have a lot of Lato and Poppins styles not loading.

**To Reproduce**
1. Add Google fonts using V1 and V2 APIs
2. Use the Google fonts optimization feature
3. See the error on the combined file

**Expected behavior**
We need a way to normalize fonts to use one API version before combining them.
Or we need to set a combined file per API version.

**Screenshots**
N/A

**Additional context**
APIs documentation: 
- V1 - https://developers.google.com/fonts/docs/getting_started
- V2 - https://developers.google.com/fonts/docs/css2

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related tickets: 

- https://secure.helpscout.net/conversation/1298260935/199079 
- https://secure.helpscout.net/conversation/1324384282/207231

**Comment by DahmaniAdame** [comment]
Related tickets: 

- https://secure.helpscout.net/conversation/1298260935/199079 
- https://secure.helpscout.net/conversation/1324384282/207231

**Comment by crystinutzaa** [comment]
### Reproduce the problem ✅ 
Reproduced on local installation

### Identify the root cause ✅ 
The root cause is the way the Google Fonts API v1 and v2 have different ways of styles and specifiers.
v1: https://fonts.googleapis.com/css?family=Cantarell:i|Droid+Serif:700
v2: https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,200..900;1,700

### Scope a solution ✅ 
There could be 2 solutions as @DahmaniAdame specified:
1. In case both Google Fonts versions are use, then use 2 combined URLs
2. Normalize the v1 into v2 and use only Google Fonts v2 

@wp-media/php what solution should be best in this case?

### Estimate the effort ✅ 
Effort `[XS]`

**Comment by piotrbak** [comment]
@crystinutzaa I was creating templates to cover tests for this issue and I found out, that we also have a problem with pure `v2` API. If the markup looks like this:
`<link href="https://fonts.googleapis.com/css2?family=Goldman:wght@400;700&family=Xanh+Mono:ital@0;1&display=swap" rel="stylesheet">`
`<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Markazi+Text:wght@450" />`

The Goldman font gets removed. You can see this here:
https://rocketlabsqa.dev/combine-v2-fonts/

**Comment by crystinutzaa** [comment]
@piotrbak  this issue has it's own github issue: https://github.com/wp-media/wp-rocket/issues/3099

**Comment by iCaspar** [comment]
We are going to have to build a new class to optimize the v2 API. Why?

The differences between the 2 apis are _significant_, the normalization solution is fought with complexity and peril.
The apis, as noted above, use different urls, so we cannot combine all font tags into a single tag without normalization. Pages using both apis will need both links, each combining all the tags of that version into a single tag.

After further research, the best approach appears to be building a new class to handle the new API, and calling the appropriate one(s) in the optimization process. When both return a combined tag, we can also add an inline html comment that explains why there are 2 GF tags remaining. We should probably also develop docs (@webtrainingwheels ) to guide customers about how they can move all their GFs to the new API in order to get back to a single GF tag.

Dev team agrees that this is better done in the 3.8 major to allow time for developing the new class, and coordinating docs, etc.

**Comment by iCaspar** [comment]
New Solution scope:
- [ ] Create new Optimization class to optimize GF APIv2.
- [ ] Add the new class to the `Optimization/GoogleFonts/Subscriber` and the `Optimization/ServiceProficer`
- [ ] Modify `Optimization\GoogleFonts\Subscriber::process() to run both optimizations and add html comment when both return a tag.
- [ ] New Unit tests for new class.
- [ ] Add testcases covering APIv2 and combined APIs to Integration tests for `GoogleFonts\Subscriber\process()`
