### ISSUE TITLE
3.8 pre-release checklist

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#3367]
This card identifies all of the tasks that need to be completed for the major release. Each task owner is responsible to communicate in this card about status and check when done and ready.

These tasks need to be completed _before_ we can proceed with the 3.8 release:

Tasks belonging to the Dev Scrum Team @wp-media/php:

- [x] Merge all PRs for this major release.
- [x] Close all issue cards that will ship in this major release.
- [x] Identify any non-merged items that are needed for this major release (comment below).
   -  [x] Get all of them completed, through QA, and merged.
- [x] Do final QA on the completed release branch (one last check to ensure everything works as expected when merged together). @wp-media/qa 
- [x] Release any dependencies, such as Lazy Load Common library or other modules/libraries.
- [x] Create the changelog and review with @arunbasillal.
- [x] Create draft feature documents in Notion, if applicable.
- [x] Create the translations/transifex.

Tasks belonging to others:

- [x] Notify Ian. Owned by @hellofromtonya @arunbasillal @GeekPress 
- [x] Notify Agathe. Owned by @hellofromtonya @arunbasillal @GeekPress 
- [ ] Finish documentation. Owned by @webtrainingwheels
- [ ] Support is ready.
- [x] Product approves the release. Owned by @arunbasillal  or @GeekPress

**Comment by Tabrisrp** [comment]
### Feature docs and demos
#### Defer JS updates
- [ ] Notion doc for exclude from defer UI & removal of safe mode
- [ ] Zoom demo of the feature for  the team
- [ ] Training for the support tech team, reviewing the code changes

To Do by @Tabrisrp 

#### Add missing dimensions attributes on images
- [ ] Notion doc for the new feature
- [ ] Zoom demo of the feature for  the team
- [ ] Training for the support tech team, reviewing the code changes

To-Do by @engahmeds3ed 

#### Exclude from lazyload
- [ ] Notion doc for the new UI
- [ ] Zoom demo of the feature for  the team
- [ ] Training for the support tech team, reviewing the code changes

To-Do by @iCaspar 

#### Google fonts API v2 compatibility
- [ ] Notion doc for the Google Fonts optimization update
- [ ] Zoom demo of the feature for  the team
- [ ] Training for the support tech team, reviewing the code changes

To-do by @crystinutzaa

**Comment by Tabrisrp** [comment]
### Draft changelog
- The plugin minimum requirements have been changed to PHP 7.0 and WordPress 5.2 (#3177, #3247)
- New feature: Add a new option to automatically add missing dimensions to images found on the page (#3301)
- Enhancement: Add a new UI field to exclude images/iframes from lazyload (#3076)
- Enhancement: Add a new UI field to exclude files from defer JS (#3233)
- Enhancement: Remove the defer JavaScript safe mode sub-option, replacing it with a better approach to handle jQuery compatibility (#3303)
- Enhancement: Update our Google fonts optimization feature to be compatible with the new Google fonts API version 2 (#3264)
- Enhancement: Add Apache rewrite rules to follow the permalink settings and redirect to the appropriate URL with or without trailingslash, event when the page is cached (#3354)
- Enhancement: The disable emoji feature is now automatically enabled, and its UI removed from the settings page (#3066)
- Enhancement: The preload links & control heartbeat options are now enabled by default for new installs (#3234)
- Enhancement: The "minutes" value for the cache lifespan has been removed (#3267)
- Bugfix: Prevent PHP notices when running on PHP 8 (#3249)
- Bugfix: Prevent warning when installating the plugin via composer (#3321)

**Comment by arunbasillal** [comment]
@Tabrisrp @webtrainingwheels Shouldn't we mention these two issues in the changelog as well? Could be useful for some users. 

- https://github.com/wp-media/wp-rocket/issues/960
- https://github.com/wp-media/wp-rocket/issues/1232

I am not sure if we should mention this one - https://github.com/wp-media/wp-rocket/issues/2773. This might need more explanation than a note in the changelog. It will look as if we are removing the beta program.

**Comment by webtrainingwheels** [comment]
I agree, @arunbasillal mentioning 960 and 1232 could be  useful.

> It will look as if we are removing the beta program.
We are!

**Comment by arunbasillal** [comment]
@webtrainingwheels Indeed we are 😂 
@Tabrisrp Let's mention https://github.com/wp-media/wp-rocket/issues/2773 in the changelog as well? I will ping Agathe and suggest we add some more explanation in our release material. Thanks for the other additions to the changelog 🙏
