### ISSUE TITLE
Release Checklist 3.8.1

### ISSUE THREAD

**Issue by iCaspar** [wp-media/wp-rocket#3430]
This card identifies all of the tasks that need to be completed for the 3.8.1 minor release. Each task owner is responsible to communicate in this card about status and check when done and ready.

These tasks need to be completed before we can proceed with the 3.6.3 release:

Tasks belonging to the Dev Scrum Team @wp-media/php:

- [X] Merge all PRs for this minor release.
- [X] Close all issue cards that will ship in this minor release.
- [X] QA on all PRs included in the release.

- [x] Final QA on the completed release branch. @wp-media/qa

- [x] Create the changelog (Draft in comment below)

Tasks belonging to others:

- [x] Notify Ian. Owned by @hellofromtonya @arunbasillal @GeekPress
- [x] Notify Agathe. Owned by @hellofromtonya @arunbasillal @GeekPress
- [x] Finish documentation. Owned by @webtrainingwheels
- [x] Support is ready. Owned by @Ian793 
- [x] Product approves the release. Owned by @arunbasillal or @GeekPress

**Comment by iCaspar** [comment]
## Changelog: (Draft)

* Bugfix: JavaScript Defer no longer breaks Smart Slider 3 (#3421)
* Bugfix: Remedy compatibility with Aveda Builder's Google Maps display (#3408)
* Bugfix: Set correct date for non-grandfathered customer account creation date to prevent showing incorrect renewal offers (#3388)
* Other: Remove the "Remove jQuery Migrate" option (#3413)

**Comment by hellofromtonya** [comment]
@webtrainingwheels Are there any documentation needs for this minor release? If yes, please advise on when will be ready.

**Comment by webtrainingwheels** [comment]
@hellofromtonya Docs changes are in draft, ready for release.  ( I thought we only did these checklists for majors?)

**Comment by hellofromtonya** [comment]
As for the checklist, I thought so too. But minor checklists are helpful too. Gets us all on the same page :)

**Comment by hellofromtonya** [comment]
Per @piotrbak in Slack:

>The QA for 3.8.1 is finished. Everything working as expected:

[testrail-report-92.pdf](https://github.com/wp-media/wp-rocket/files/5726790/testrail-report-92.pdf)

**Comment by arunbasillal** [comment]
Everything is good to go from product side. 

@vmanthos said:

> Support is good, even more since 3.8.1 is probably going to reduce the number of tickets with the removal of Remove Query Migrate. 🙏 

Whenever you are ready, please go ahead with the release @iCaspar @engahmeds3ed

**Comment by engahmeds3ed** [comment]
Ok, I'm preparing that now.
