### ISSUE TITLE
3.9 release checklist

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#3780]
This card identifies all of the tasks that need to be completed for the major release. Each task owner is responsible to communicate in this card about status and check when done and ready.

These tasks need to be completed _before_ we can proceed with the 3.9 release:

Tasks belonging to the Dev Scrum Team @wp-media/php:

- [x] Merge all PRs for this major release.
- [x] Close all issue cards that will ship in this major release.
- [x] Identify any non-merged items that are needed for this major release (comment below).
   -  [x] Get all of them completed, through QA, and merged.
- [x] Do final QA on the completed release branch (one last check to ensure everything works as expected when merged together). @wp-media/qa 
- [x] Create the changelog.
- [x] Update/create draft feature documents in Notion, if applicable.
- [x] Update the translations/transifex.

Tasks belonging to others:

- [x] Notify Ian. Owned by @Tabrisrp  @GeekPress 
- [x] Notify Agathe. Owned by @Tabrisrp @GeekPress 
- [x] Finish documentation. Owned by @webtrainingwheels
- [x] Support is ready. Owned by @Ian793 
- [x] Product approves the release. Owned by @GeekPress

**Comment by remyperona** [comment]
Delay JS feature doc in notion updated

**Comment by remyperona** [comment]
New strings have been pushed to Transifex for translation

**Comment by remyperona** [comment]
#### Changelog
- This version requires the WordPress version to be 5.3 or above
- New feature: Remove Unused CSS. This feature removes all the unused CSS from the page, reducing page size and lower the number of HTTP request (#3635)
- Enhancement: new version of our delay JS feature. It is now applied on all javascript files by default, instead of using an inclusion list (#3738)
- Google & Facebook tracking one-click add-ons have been removed. We now recommend to use the delay JS option to optimize loading of those 3rd party scripts (#3597)
- Bugfix: Prevent caching of incomplete pages to avoid blank pages (#2776)
- Regression fix: Revert the removal of the preloaded fonts when CPCSS is enabled (#3785)
- 3rd party compatibility: Add compatibility with WooCommerce Multilingual currency switcher (#3418)

@GeekPress Can you validate the changelog? And update any part that would need to

**Comment by GeekPress** [comment]
@Tabrisrp We're good ;)

**Comment by jazir555** [comment]
Why hasn't this been released?

**Comment by gevcen** [comment]
> Why hasn't this been released?

You prefer to have a quick release but full of bugs? No, so please let them the time that they think necessary enough to do their job well.
