### ISSUE TITLE
Breaking Opengraph Meta for WhatsApp Link Preview

### ISSUE THREAD

**Issue by mehedihasanziku** [wp-media/wp-rocket#4507]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After Used CSS generated **`WhatsApp`** link preview not working properly, it's not displaying opengraph data specifically for whatsapp.

**To Reproduce**

1. Enable Remove Unsed CSS
2. [Used Snippets](https://github.com/wp-media/wp-rocket-helpers/blob/master/static-files/wp-rocket-no-rucss-for-page/wp-rocket-no-rucss-for-page.php) to disable rucss pagewise 
3. Whatsapp stored cache for every new query string, so i tested `?nocache`, it's show meta fine but it's baseless because it will not give me what's the thing of rocket causing that issue because it will disable all wprocket optimization. so i looked for [article](https://docs.wp-rocket.me/article/971-caching-query-strings)  which will show cached version with random string and used `?fbclid=random-string` this gives me accurate result on real-time. so when i **`used (#2) snippet`** it shows opengraph data properly, else it's shows only page title.

**Expected behavior**
Opengraph Meta should display properly

**Screenshots**
N/A

**Additional context**
It may solve if we change used css position after Opengraph meta end or before closing `</head>`
- This issues isn't visible on else places like Facebook debugger tool or FB Preview

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1693016896/307051/
Facebook debugger is not showing any issues. 
Opengraph data are not altered when adding the Used CSS. 
PS.: Moving the Used CSS below the OpenGraph markup didn't fix the issue.

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1717570783/312730

**Comment by girlie** [comment]
Pursuant to a discussion we just had in Slack, about another customer's ticket here:

https://secure.helpscout.net/conversation/1715901852/312457/

...the conclusion was that we should probably just not serve cached pages to WhatsApp in the first place (e.g., by blocking their User Agent).

Another ticket was also mentioned during that discussion, so I'll drop it here as well:

https://secure.helpscout.net/conversation/1706226099/309914/

Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1638889434195000

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1717998293/312802

**Comment by camilamadronero-zz** [comment]
New one https://secure.helpscout.net/conversation/1720452797/313220/

**Comment by girlie** [comment]
Another: https://secure.helpscout.net/conversation/1723300434/313723/

**Comment by remyperona** [comment]
@piotrbak Do we want to go with the user agent exclusion for this one?

**Comment by piotrbak** [comment]
@Tabrisrp Yes, this seems like the best way out. We need to be sure to exclude a very unique user agent though.

**Comment by remyperona** [comment]
They seem to use `WhatsApp` in their UA, so it should be specific enough?

**Comment by piotrbak** [comment]
Yes, I think you're right

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `inc/functions/options.php`, function `get_rocket_cache_reject_ua()`

Add `$ua[] = 'WhatsApp';` on line 408

### Estimate the effort ✅
Effort `[XS]`

**Comment by alfonso100** [comment]
@camilamadronero new doc in draft state, to be published when the PR is released:
https://docs.wp-rocket.me/article/1665-enable-cache-for-whatsapp-agent?preview=61cbd61a6e49f25358bc9614

(it is almost a clone of the Facebook one)

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1882881657/342810/
@piotrbak we might need to reopen this one. 
The implemented fix doesn't cover scenarios with other cache tiers where the cached version with the RUCSS will still be sent to WhatsApp.

**Comment by piotrbak** [comment]
@DahmaniAdame what do you mean by other cache? Server side caching mechanisms?

**Comment by DahmaniAdame** [comment]
@piotrbak yes. The fix won't work if the server-side cache doesn't bypass their cache when the WhatsApp user agent.

**Comment by piotrbak** [comment]
@DahmaniAdame But we're excluding this UA from every optimization from our end. Why our optimizations are applied then?

**Comment by DahmaniAdame** [comment]
@piotrbak that's true on websites without server-side or DNS-side cache. WP Rocket is directly handling requests and will be able to bypass cache. 

If there are other caching layers, the response will be an optimized page as the other caching layer is not set to bypass cache if the request comes from WhatsApp, and they preceed WP Rocket's cache. And consequently will trigger the issue with RUCSS and WhatsApp.

Try this on a website with a server-side or a DNS-side cache. 

Let's assume the website has lazyload enabled for testing as this will require checking the response, and checking RUCSS won't be practical.

Do a first visit to make sure the page is cached:

```
curl https://domain.ext/ | grep "window.lazyLoadOptions"
```

In this case, the expected response is: 

```
<script>window.lazyLoadOptions={elements_selector:"img[data-lazy-src] ... 
```

And then, test with a WhatApps UA: 


```
curl -A "WhatsApp/2.21.221.1 i" https://domain.ext/ | grep "window.lazyLoadOptions"
```

That should return an empty response. But when other caching layers are enabled, the response will be: 

```
<script>window.lazyLoadOptions={elements_selector:"img[data-lazy-src] ... 
```

Meaning that the optimized version that we wanted to avoid for WhatsApp is still delivered in that case.

**Comment by mehedihasanziku** [comment]
I haven't tested this case such way, thanks for enlighten me another way to debug.

I think this issue will not be there if wprocket decided to use **RUCSS FileSystem Method**, but still this thread cases should be considered for future edge case
