### ISSUE TITLE
Conflict between WPR and Cloudinary at out latest release

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#4518]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version: **3.10.3**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
```
[19-Nov-2021 16:28:32 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WP_Rocket\Engine\Media\Lazyload\Subscriber::maybe_disable_core_lazyload(), 1 passed in /www/htdocs/xxx/xxx.de/wp-includes/class-wp-hook.php on line 303 and exactly 2 expected in /www/htdocs/xxx/xxx.de/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php:467
Stack trace:
#0 /www/htdocs/xxx/xxx.de/wp-includes/class-wp-hook.php(303): WP_Rocket\Engine\Media\Lazyload\Subscriber->maybe_disable_core_lazyload(true)
#1 /www/htdocs/xxx/xxx.de/wp-includes/plugin.php(189): WP_Hook->apply_filters(true, Array)
#2 /www/htdocs/xxx/xxx.de/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/media/class-filter.php(382): apply_filters('wp_lazy_loading...', true)
#3 /www/htdocs/xxx/xxx.de/wp-includes/class-wp-hook.php(303): Cloudinary\Media\Filter->filter_out_local('<p><img width="...')
#4 /www/htdocs/xxx/ in /www/htdocs/xxx/xxx.de/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php on line 467
```

This error is because this cloudinary plugin is creating the filter `wp_lazy_loading_enabled` here
https://plugins.trac.wordpress.org/browser/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/trunk/php/media/class-filter.php#L382

with only one argument but WordPress is creating it with more than one argument here:
https://github.com/wordpress/wordpress-develop/blob/d96e75674b63c09196e0c82732bb6377408b1cfd/src/wp-includes/media.php#L1746

and we use this filter here:
https://github.com/wp-media/wp-rocket/blob/f48cb29346ab9a4f42c39d01f14e024b9a31086a/inc/Engine/Media/Lazyload/Subscriber.php#L84

and our code needs two arguments which isn't available from cloudinary plugin code.

**To Reproduce**
## Using cloudinary plugin

1. Install cloudinary along with WPR 3.10.3
2. Once both are installed you will find a fatal error inside debug.log

## Using custom code (Simple way to reproduce the issue)
1. Add the following code into your current active theme's `functions.php` file
```
apply_filters( 'wp_lazy_loading_enabled', true);
```
2. Activate WPR 3.10.3
3. Check debug.log file to see the fatal error

**Expected behavior**
No error should happen.
We know that the main problem is on their plugin but after discussing with @wp-media/php team, we can guard our code not to have this issue happening.

**Additional context**
@alfonso100 Contacted the plugin on WP.org and they replied that this will be solved on their next release: https://wordpress.org/support/topic/incorrect-usage-of-apply_filterwp_lazy_loading_enabled/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
Add default value for `$tag_name` argument here: https://github.com/wp-media/wp-rocket/blob/f48cb29346ab9a4f42c39d01f14e024b9a31086a/inc/Engine/Media/Lazyload/Subscriber.php#L467
to be like that
```
public function maybe_disable_core_lazyload( $value, $tag_name = 'img' ) {
```
- [x] Estimate the effort **[XS]**

**Comment by NataliaDrause** [comment]
The same error caused by the Strong Testimonial Plugin: https://strongtestimonials.com/

Ticket: https://secure.helpscout.net/conversation/1829916569/334214/

Error:
```
PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function WP_Rocket\Engine\Media\Lazyload\Subscriber::maybe_disable_core_lazyload(), 1 passed in /home/styleplu/public_html/wp-includes/class-wp-hook.php on line 292 and exactly 2 expected in /home/styleplu/public_html/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php:467
Stack trace:
#0 /home/styleplu/public_html/wp-includes/class-wp-hook.php(292): WP_Rocket\Engine\Media\Lazyload\Subscriber->maybe_disable_core_lazyload(true)
#1 /home/styleplu/public_html/wp-includes/plugin.php(212): WP_Hook->apply_filters(true, Array)
#2 /home/styleplu/public_html/wp-content/plugins/strong-testimonials/includes/functions-image.php(127): apply_filters('wp_lazy_loading...', true)
#3 /home/styleplu/public_html/wp-includes/class-wp-hook.php(292): wpmtst_add_lazyload(Array, Object(WP_Post), 'full')
#4 /home/styleplu/public_html/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array)
#5 /home/styleplu/public_html/wp-includes/media.php(1090): apply_filte in /home/styleplu/public_html/wp-content/plugins/wp-rocket/inc/Engine/Media/Lazyload/Subscriber.php on line 467
```

**Comment by NataliaDrause** [comment]
I reported the above-mentioned error to the Strong Testimonials team.
Ticket: https://secure.helpscout.net/conversation/1832468964/334814/

**Comment by wordpressfan** [comment]
The issue is still there, @alfonso100 can u plz reply to that ticket informing them that it's not solved yet, they can find the code here in latest release:

https://plugins.trac.wordpress.org/browser/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/trunk/php/media/class-filter.php#L351

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.

**Comment by jqmg** [comment]
I'm seeing this problem as well. Here are my specs:

WordPress 6.8.1 
WP Rocket - Version 3.19.1.2 
PHP 8.3.22
