### ISSUE TITLE
Exclude getresponse.com tracker from JavaScript minification

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4973]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.0.5`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

When `ga.getresponse.com/script/ga.js` is minified and hosted, it returns the following console error: 

```
Uncaught SyntaxError: Unexpected token ':'
```

Checking the resulting file content when hosted `/cache/min/1/script/ga.js` gives the following: 

Excluding `ga.getresponse.com/script/ga.js` from JavaScript minification fixes the issue.

**To Reproduce**
1. Use GetResponse tracker
2. Enable JS minification
3. See error

**Expected behavior**
No error should result from using GetResponse tracker with JS minify. 

**Screenshots**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1863039875/339770/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort
